---
- name: Change Password for user "avinash"
  hosts: junos
  connection: netconf
  gather_facts: no
  vars_prompt:
    - name: uname
      prompt: "Enter Your Username to login to the device" # Promp the message while asking for user's input
      private: no # Make the text visible to users
    - name: passwd
      prompt: "Enter Your Password of above username"
      private: yes # Make the text invisible to users
      unsafe: yes # Allows special characters input by user. Its required especially in passwords.
    - name: new_user
      prompt: "Enter the Username that needs Password Change"
      private: no
      unsafe: yes
    - name: new_pass
      prompt: "Enter new password for the Username of target account"
      private: no
      unsafe: yes
      encrypt: sha512_crypt
      salt_size: 7

  tasks:
    - name: Get confirmation from user
      pause:
        prompt: "Are you sure you want to change password for '{{new_user}}'? (yes/no)"
      register: confirmation
    # - name: Print confirmation
    #   debug: msg={{confirmation}}
    - name: Changing password for the user "avinash"
      junos_user:
        name: "{{new_user}}" ## Username
        encrypted_password: "{{new_pass}}"
        role: super-user # Defines the role of the user
        state: present # Makes sure the username is available on device. If not present, it will create one.
      register: output
      when: (confirmation.user_input == 'yes') or (confirmation.user_input == 'y') or (confirmation.user_input == 'Yes') or (confirmation.user_input == 'YES') or (confirmation.user_input == 'Y')
    - name: Print output
      debug:
        msg: "{{output}}"
