---
- name: Validate Internet via 4.2.2.2
  hosts: junos
  tasks:
    - name: Ping Global DNS
      junos_ping:
        dest: 4.2.2.2
        size: 1024
        ttl: 128
        source: 10.0.0.14
        count: 10
###########################################################
############# NOT WORKING #################################
###########################################################
